name: inventorio
description: Basic home inventory in Flutter
version: 1.0.2+55

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^0.3.0
  uuid: ^2.0.0
  qr_mobile_vision: ^0.1.0
  image_picker: ^0.4.10
  path_provider: ^0.5.0+1
  quiver_hashcode: ^2.0.0
  google_sign_in: ^3.2.4
  firebase_analytics: ^1.0.6
  firebase_auth: ^0.6.6
  cloud_firestore: ^0.8.2+3
  firebase_storage: ^1.0.4
  json_annotation: ^2.0.0
  intl: ^0.15.7
  #qr_flutter: ^1.1.6
  shared_preferences: ^0.4.3
  date_utils: ^0.1.0+2
  flutter_local_notifications: ^0.4.2
  flutter_slidable: ^0.4.9
  logging: ^0.11.3+2
  cached_network_image: ^0.6.0+1
  flutter_simple_dependency_injection: ^1.0.0
  rxdart: ^0.20.0
  font_awesome_flutter: ^8.2.0
  url_launcher: ^5.0.1
  package_info: ^0.4.0+1
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
      ref: 2.0.0-dev


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^2.0.2
  flutter_launcher_icons: ^0.6.1
  mockito: ^4.0.0
  mock_data: ^1.2.5

flutter_icons:
  android: true
  ios: true
  image_path: resources/icons/icon.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: resources/fonts/NotoSans/NotoSans-Medium.ttf
        - asset: resources/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: resources/fonts/Raleway/Raleway-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: resources/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Prompt
      fonts:
        - asset: resources/fonts/Prompt/Prompt-Regular.ttf
        - asset: resources/fonts/Prompt/Prompt-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: resources/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: resources/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - resources/icons/icon.png
    - resources/icons/icon_transparent.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
